//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porno_Graphic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Enable/disable display of the grid in the Tile Editor.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Enable/disable display of the grid in the Tile Editor.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditorGrid {
            get {
                return ((bool)(this["EditorGrid"]));
            }
            set {
                this["EditorGrid"] = value;
            }
        }
        
        /// <summary>
        /// Enable/disable display of the grid in the Tile Arranger.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Enable/disable display of the grid in the Tile Arranger.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArrangerGrid {
            get {
                return ((bool)(this["ArrangerGrid"]));
            }
            set {
                this["ArrangerGrid"] = value;
            }
        }
        
        /// <summary>
        /// Enable/disable display of the grid in the Tile Viewer.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Enable/disable display of the grid in the Tile Viewer.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewerGrid {
            get {
                return ((bool)(this["ViewerGrid"]));
            }
            set {
                this["ViewerGrid"] = value;
            }
        }
        
        /// <summary>
        /// Default color of the Tile Editor grid.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default color of the Tile Editor grid.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color EditorGridColor {
            get {
                return ((global::System.Drawing.Color)(this["EditorGridColor"]));
            }
            set {
                this["EditorGridColor"] = value;
            }
        }
        
        /// <summary>
        /// Default color of the Tile Arranger grid.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default color of the Tile Arranger grid.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ArrangerGridColor {
            get {
                return ((global::System.Drawing.Color)(this["ArrangerGridColor"]));
            }
            set {
                this["ArrangerGridColor"] = value;
            }
        }
        
        /// <summary>
        /// Default color of the Tile Viewer grid.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default color of the Tile Viewer grid.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ViewerGridColor {
            get {
                return ((global::System.Drawing.Color)(this["ViewerGridColor"]));
            }
            set {
                this["ViewerGridColor"] = value;
            }
        }
    }
}
